services:
  
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=devUser
      - POSTGRES_PASSWORD=devPass1
      - POSTGRES_DB=concreteiot
    ports:
      - '5432:5432'